### ISSUE TITLE
1.0.11-armv6 on rpi3 fails to run

### ISSUE THREAD

**Issue by michaelbub** [bauerj/borg-binaries#5]
root@DietPi:~# ./borg-1.0.11-armv6
Traceback (most recent call last):
  File "borg/__main__.py", line 1, in <module>
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/site-packages/PyInstaller-3.2.1-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "borg/__init__.py", line 3, in <module>
ImportError: No module named 'borg._version'
Failed to execute script __main__

1.0.10 works

**Comment by bauerj** [comment]
Thanks for reporting!

The issue seems to be related to an outdated requirement, which I updated manually. I've started a new build right now that will also update the built-in Python version. It will probably take a few hours to complete.

**Comment by michaelbub** [comment]
Can confirm that it works now
